//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePayTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cafao_dtl_tbl
    {
        public string payroll_year { get; set; }
        public string payroll_registry_nbr { get; set; }
        public int seq_nbr { get; set; }
        public string function_code { get; set; }
        public string allotment_code { get; set; }
        public string account_code { get; set; }
        public string account_short_title { get; set; }
        public Nullable<decimal> account_amt { get; set; }
        public string created_by_user { get; set; }
        public string updated_by_user { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public Nullable<int> raao_code { get; set; }
        public Nullable<int> ooe_code { get; set; }
    }
}
