//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePayTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edocument_trk_nbrs_tbl
    {
        public string doc_ctrl_nbr { get; set; }
        public string doc_fund_subcode { get; set; }
        public string doc_pbo_nbr { get; set; }
        public string doc_cafoa { get; set; }
        public string doc_voucher_nbr { get; set; }
        public string doc_pto_nbr { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public string created_user_id { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string updated_user_id { get; set; }
    }
}
