//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePayTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edoc_route_ovrd_tbl
    {
        public string department_code { get; set; }
        public string to_dept_code { get; set; }
        public string rte_descr { get; set; }
    }
}
