//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePayTrack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRIS_TRKEntities : DbContext
    {
        public HRIS_TRKEntities()
            : base("name=HRIS_TRKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<document_route_funds_tbl> document_route_funds_tbl { get; set; }
        public virtual DbSet<document_route_tbl> document_route_tbl { get; set; }
        public virtual DbSet<document_route_users_tbl> document_route_users_tbl { get; set; }
        public virtual DbSet<document_tracking_link_tbl> document_tracking_link_tbl { get; set; }
        public virtual DbSet<document_tracking_nbrs_tbl> document_tracking_nbrs_tbl { get; set; }
        public virtual DbSet<document_tracking_tbl> document_tracking_tbl { get; set; }
        public virtual DbSet<document_type_tbl> document_type_tbl { get; set; }
        public virtual DbSet<edoc_route_dept_tbl> edoc_route_dept_tbl { get; set; }
        public virtual DbSet<edoc_route_ovrd_tbl> edoc_route_ovrd_tbl { get; set; }
        public virtual DbSet<edocument_trk_nbrs_tbl> edocument_trk_nbrs_tbl { get; set; }
        public virtual DbSet<edocument_trk_payroll_tbl> edocument_trk_payroll_tbl { get; set; }
        public virtual DbSet<edocument_trk_tbl> edocument_trk_tbl { get; set; }
        public virtual DbSet<vw_cashadv_ada_list> vw_cashadv_ada_list { get; set; }
        public virtual DbSet<vw_cashadv_fund_sub_tbl_TRK> vw_cashadv_fund_sub_tbl_TRK { get; set; }
        public virtual DbSet<vw_cashadv_list> vw_cashadv_list { get; set; }
        public virtual DbSet<vw_department_tbl_list_TRK> vw_department_tbl_list_TRK { get; set; }
        public virtual DbSet<vw_document_tracking_link_tbl> vw_document_tracking_link_tbl { get; set; }
        public virtual DbSet<vw_document_tracking_tbl_2be_rcvd_07> vw_document_tracking_tbl_2be_rcvd_07 { get; set; }
        public virtual DbSet<vw_document_tracking_tbl_2be_rcvd_07_owner> vw_document_tracking_tbl_2be_rcvd_07_owner { get; set; }
        public virtual DbSet<vw_document_tracking_tbl_2be_rcvd_all> vw_document_tracking_tbl_2be_rcvd_all { get; set; }
        public virtual DbSet<vw_document_tracking_tbl_2be_rcvd_oth> vw_document_tracking_tbl_2be_rcvd_oth { get; set; }
        public virtual DbSet<vw_document_tracking_tbl_2be_rlsd_03> vw_document_tracking_tbl_2be_rlsd_03 { get; set; }
        public virtual DbSet<vw_document_tracking_tbl_2be_rlsd_07> vw_document_tracking_tbl_2be_rlsd_07 { get; set; }
        public virtual DbSet<vw_document_tracking_tbl_2be_rlsd_all> vw_document_tracking_tbl_2be_rlsd_all { get; set; }
        public virtual DbSet<vw_document_tracking_tbl_2be_rlsd_oth> vw_document_tracking_tbl_2be_rlsd_oth { get; set; }
        public virtual DbSet<vw_edocument_trk_tbl_return> vw_edocument_trk_tbl_return { get; set; }
        public virtual DbSet<vw_functions_tbl_list_TRK> vw_functions_tbl_list_TRK { get; set; }
        public virtual DbSet<vw_payregistry_CA_ADA_info_list> vw_payregistry_CA_ADA_info_list { get; set; }
        public virtual DbSet<vw_payregistry_CA_info_list> vw_payregistry_CA_info_list { get; set; }
        public virtual DbSet<vw_payrollemployeegroupings_HRIS_TRK> vw_payrollemployeegroupings_HRIS_TRK { get; set; }
        public virtual DbSet<vw_payrollregistry_info2_HRIS_TRK> vw_payrollregistry_info2_HRIS_TRK { get; set; }
        public virtual DbSet<vw_edocument_trk_tbl_2be_rcvd> vw_edocument_trk_tbl_2be_rcvd { get; set; }
        public virtual DbSet<vw_document_tracking_tbl_2be_rlsd_cr> vw_document_tracking_tbl_2be_rlsd_cr { get; set; }
        public virtual DbSet<cafao_dtl_tbl> cafao_dtl_tbl { get; set; }
        public virtual DbSet<vw_edocument_trk_tbl_2be_rlsd> vw_edocument_trk_tbl_2be_rlsd { get; set; }
    
        public virtual ObjectResult<document_type_tbl_list_Result> document_type_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<document_type_tbl_list_Result>("document_type_tbl_list");
        }
    
        public virtual ObjectResult<sp_cafao_dtl_tbl_list_Result> sp_cafao_dtl_tbl_list(string par_payroll_year, string par_payroll_registry_nbr)
        {
            var par_payroll_yearParameter = par_payroll_year != null ?
                new ObjectParameter("par_payroll_year", par_payroll_year) :
                new ObjectParameter("par_payroll_year", typeof(string));
    
            var par_payroll_registry_nbrParameter = par_payroll_registry_nbr != null ?
                new ObjectParameter("par_payroll_registry_nbr", par_payroll_registry_nbr) :
                new ObjectParameter("par_payroll_registry_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cafao_dtl_tbl_list_Result>("sp_cafao_dtl_tbl_list", par_payroll_yearParameter, par_payroll_registry_nbrParameter);
        }
    
        public virtual ObjectResult<sp_document_tracking_nbrs_tbl_update_Result> sp_document_tracking_nbrs_tbl_update(string p_doc_ctrl_nbr, string p_doc_fund_subcode, string p_doc_nbr, string p_department_code, Nullable<System.DateTime> p_doc_dttm, string p_doc_user_id)
        {
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            var p_doc_fund_subcodeParameter = p_doc_fund_subcode != null ?
                new ObjectParameter("p_doc_fund_subcode", p_doc_fund_subcode) :
                new ObjectParameter("p_doc_fund_subcode", typeof(string));
    
            var p_doc_nbrParameter = p_doc_nbr != null ?
                new ObjectParameter("p_doc_nbr", p_doc_nbr) :
                new ObjectParameter("p_doc_nbr", typeof(string));
    
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_doc_dttmParameter = p_doc_dttm.HasValue ?
                new ObjectParameter("p_doc_dttm", p_doc_dttm) :
                new ObjectParameter("p_doc_dttm", typeof(System.DateTime));
    
            var p_doc_user_idParameter = p_doc_user_id != null ?
                new ObjectParameter("p_doc_user_id", p_doc_user_id) :
                new ObjectParameter("p_doc_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_document_tracking_nbrs_tbl_update_Result>("sp_document_tracking_nbrs_tbl_update", p_doc_ctrl_nbrParameter, p_doc_fund_subcodeParameter, p_doc_nbrParameter, p_department_codeParameter, p_doc_dttmParameter, p_doc_user_idParameter);
        }
    
        public virtual ObjectResult<sp_document_tracking_return_2_route_Result> sp_document_tracking_return_2_route(string p_department_code, string p_doc_ctrl_nbr)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_document_tracking_return_2_route_Result>("sp_document_tracking_return_2_route", p_department_codeParameter, p_doc_ctrl_nbrParameter);
        }
    
        public virtual ObjectResult<sp_document_tracking_tbl_2be_rcvd_Result> sp_document_tracking_tbl_2be_rcvd(string p_role_id, string p_department_code)
        {
            var p_role_idParameter = p_role_id != null ?
                new ObjectParameter("p_role_id", p_role_id) :
                new ObjectParameter("p_role_id", typeof(string));
    
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_document_tracking_tbl_2be_rcvd_Result>("sp_document_tracking_tbl_2be_rcvd", p_role_idParameter, p_department_codeParameter);
        }
    
        public virtual ObjectResult<sp_document_tracking_tbl_2be_rlsd_Result> sp_document_tracking_tbl_2be_rlsd(string p_role_id, string p_department_code)
        {
            var p_role_idParameter = p_role_id != null ?
                new ObjectParameter("p_role_id", p_role_id) :
                new ObjectParameter("p_role_id", typeof(string));
    
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_document_tracking_tbl_2be_rlsd_Result>("sp_document_tracking_tbl_2be_rlsd", p_role_idParameter, p_department_codeParameter);
        }
    
        public virtual ObjectResult<sp_document_tracking_tbl_CA_link_list_Result> sp_document_tracking_tbl_CA_link_list(string p_doc_ctrl_nbr)
        {
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_document_tracking_tbl_CA_link_list_Result>("sp_document_tracking_tbl_CA_link_list", p_doc_ctrl_nbrParameter);
        }
    
        public virtual ObjectResult<sp_document_tracking_tbl_history_Result> sp_document_tracking_tbl_history(string p_doc_ctrl_nbr, string p_docmnt_type)
        {
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            var p_docmnt_typeParameter = p_docmnt_type != null ?
                new ObjectParameter("p_docmnt_type", p_docmnt_type) :
                new ObjectParameter("p_docmnt_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_document_tracking_tbl_history_Result>("sp_document_tracking_tbl_history", p_doc_ctrl_nbrParameter, p_docmnt_typeParameter);
        }
    
        public virtual ObjectResult<sp_document_tracking_tbl_list_Result> sp_document_tracking_tbl_list(string p_payroll_year, string p_empl_id)
        {
            var p_payroll_yearParameter = p_payroll_year != null ?
                new ObjectParameter("p_payroll_year", p_payroll_year) :
                new ObjectParameter("p_payroll_year", typeof(string));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_document_tracking_tbl_list_Result>("sp_document_tracking_tbl_list", p_payroll_yearParameter, p_empl_idParameter);
        }
    
        public virtual int sp_document_tracking_tbl_rcvd_list(string p_department_code, Nullable<int> p_year, Nullable<int> p_month)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_yearParameter = p_year.HasValue ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(int));
    
            var p_monthParameter = p_month.HasValue ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_document_tracking_tbl_rcvd_list", p_department_codeParameter, p_yearParameter, p_monthParameter);
        }
    
        public virtual int sp_document_tracking_tbl_retd_list(string p_department_code, Nullable<int> p_year, Nullable<int> p_month)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_yearParameter = p_year.HasValue ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(int));
    
            var p_monthParameter = p_month.HasValue ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_document_tracking_tbl_retd_list", p_department_codeParameter, p_yearParameter, p_monthParameter);
        }
    
        public virtual int sp_document_tracking_tbl_rlsd_list(string p_department_code, Nullable<int> p_year, Nullable<int> p_month)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_yearParameter = p_year.HasValue ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(int));
    
            var p_monthParameter = p_month.HasValue ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_document_tracking_tbl_rlsd_list", p_department_codeParameter, p_yearParameter, p_monthParameter);
        }
    
        public virtual ObjectResult<sp_document_tracking_tbl_search_Result> sp_document_tracking_tbl_search(string p_search_type, string p_search_text)
        {
            var p_search_typeParameter = p_search_type != null ?
                new ObjectParameter("p_search_type", p_search_type) :
                new ObjectParameter("p_search_type", typeof(string));
    
            var p_search_textParameter = p_search_text != null ?
                new ObjectParameter("p_search_text", p_search_text) :
                new ObjectParameter("p_search_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_document_tracking_tbl_search_Result>("sp_document_tracking_tbl_search", p_search_typeParameter, p_search_textParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_nbrs_tbl_update_Result> sp_edocument_trk_nbrs_tbl_update(string p_doc_ctrl_nbr, string p_doc_fund_subcode, string p_doc_nbr, string p_doc_cafoa, string p_department_code, Nullable<System.DateTime> p_doc_dttm, string p_doc_user_id)
        {
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            var p_doc_fund_subcodeParameter = p_doc_fund_subcode != null ?
                new ObjectParameter("p_doc_fund_subcode", p_doc_fund_subcode) :
                new ObjectParameter("p_doc_fund_subcode", typeof(string));
    
            var p_doc_nbrParameter = p_doc_nbr != null ?
                new ObjectParameter("p_doc_nbr", p_doc_nbr) :
                new ObjectParameter("p_doc_nbr", typeof(string));
    
            var p_doc_cafoaParameter = p_doc_cafoa != null ?
                new ObjectParameter("p_doc_cafoa", p_doc_cafoa) :
                new ObjectParameter("p_doc_cafoa", typeof(string));
    
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_doc_dttmParameter = p_doc_dttm.HasValue ?
                new ObjectParameter("p_doc_dttm", p_doc_dttm) :
                new ObjectParameter("p_doc_dttm", typeof(System.DateTime));
    
            var p_doc_user_idParameter = p_doc_user_id != null ?
                new ObjectParameter("p_doc_user_id", p_doc_user_id) :
                new ObjectParameter("p_doc_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_nbrs_tbl_update_Result>("sp_edocument_trk_nbrs_tbl_update", p_doc_ctrl_nbrParameter, p_doc_fund_subcodeParameter, p_doc_nbrParameter, p_doc_cafoaParameter, p_department_codeParameter, p_doc_dttmParameter, p_doc_user_idParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_return_2_route_Result> sp_edocument_trk_return_2_route(string p_department_code, string p_doc_ctrl_nbr)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_return_2_route_Result>("sp_edocument_trk_return_2_route", p_department_codeParameter, p_doc_ctrl_nbrParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_tbl_CA_ADA_link_list_Result> sp_edocument_trk_tbl_CA_ADA_link_list(string p_doc_ctrl_nbr)
        {
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_tbl_CA_ADA_link_list_Result>("sp_edocument_trk_tbl_CA_ADA_link_list", p_doc_ctrl_nbrParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_tbl_search_Result> sp_edocument_trk_tbl_search(string p_search_type, string p_search_text)
        {
            var p_search_typeParameter = p_search_type != null ?
                new ObjectParameter("p_search_type", p_search_type) :
                new ObjectParameter("p_search_type", typeof(string));
    
            var p_search_textParameter = p_search_text != null ?
                new ObjectParameter("p_search_text", p_search_text) :
                new ObjectParameter("p_search_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_tbl_search_Result>("sp_edocument_trk_tbl_search", p_search_typeParameter, p_search_textParameter);
        }
    
        public virtual ObjectResult<sp_employmenttypes_tbl_list_Result> sp_employmenttypes_tbl_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_employmenttypes_tbl_list_Result>("sp_employmenttypes_tbl_list");
        }
    
        public virtual ObjectResult<sp_modules_tbl_list_TRK_Result> sp_modules_tbl_list_TRK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_modules_tbl_list_TRK_Result>("sp_modules_tbl_list_TRK");
        }
    
        public virtual int sp_payrollemployeemaster_tbl_insert_RE_empl_id(string p_year, string p_month, string p_user_id, string p_empl_id)
        {
            var p_yearParameter = p_year != null ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(string));
    
            var p_monthParameter = p_month != null ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(string));
    
            var p_user_idParameter = p_user_id != null ?
                new ObjectParameter("p_user_id", p_user_id) :
                new ObjectParameter("p_user_id", typeof(string));
    
            var p_empl_idParameter = p_empl_id != null ?
                new ObjectParameter("p_empl_id", p_empl_id) :
                new ObjectParameter("p_empl_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_payrollemployeemaster_tbl_insert_RE_empl_id", p_yearParameter, p_monthParameter, p_user_idParameter, p_empl_idParameter);
        }
    
        public virtual ObjectResult<sp_payrollregistry_cafao_rep_Result> sp_payrollregistry_cafao_rep(string par_payroll_year, string par_payroll_registry_nbr, string par_payrolltemplate_code)
        {
            var par_payroll_yearParameter = par_payroll_year != null ?
                new ObjectParameter("par_payroll_year", par_payroll_year) :
                new ObjectParameter("par_payroll_year", typeof(string));
    
            var par_payroll_registry_nbrParameter = par_payroll_registry_nbr != null ?
                new ObjectParameter("par_payroll_registry_nbr", par_payroll_registry_nbr) :
                new ObjectParameter("par_payroll_registry_nbr", typeof(string));
    
            var par_payrolltemplate_codeParameter = par_payrolltemplate_code != null ?
                new ObjectParameter("par_payrolltemplate_code", par_payrolltemplate_code) :
                new ObjectParameter("par_payrolltemplate_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollregistry_cafao_rep_Result>("sp_payrollregistry_cafao_rep", par_payroll_yearParameter, par_payroll_registry_nbrParameter, par_payrolltemplate_codeParameter);
        }
    
        public virtual ObjectResult<sp_payrollregistry_cafao_rep_new_Result> sp_payrollregistry_cafao_rep_new(string par_payroll_year, string par_payroll_registry_nbr, string par_payrolltemplate_code)
        {
            var par_payroll_yearParameter = par_payroll_year != null ?
                new ObjectParameter("par_payroll_year", par_payroll_year) :
                new ObjectParameter("par_payroll_year", typeof(string));
    
            var par_payroll_registry_nbrParameter = par_payroll_registry_nbr != null ?
                new ObjectParameter("par_payroll_registry_nbr", par_payroll_registry_nbr) :
                new ObjectParameter("par_payroll_registry_nbr", typeof(string));
    
            var par_payrolltemplate_codeParameter = par_payrolltemplate_code != null ?
                new ObjectParameter("par_payrolltemplate_code", par_payrolltemplate_code) :
                new ObjectParameter("par_payrolltemplate_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollregistry_cafao_rep_new_Result>("sp_payrollregistry_cafao_rep_new", par_payroll_yearParameter, par_payroll_registry_nbrParameter, par_payrolltemplate_codeParameter);
        }
    
        public virtual ObjectResult<sp_payrollregistry_cafao_sub_rep_Result> sp_payrollregistry_cafao_sub_rep(string par_payroll_year, string par_payroll_registry_nbr)
        {
            var par_payroll_yearParameter = par_payroll_year != null ?
                new ObjectParameter("par_payroll_year", par_payroll_year) :
                new ObjectParameter("par_payroll_year", typeof(string));
    
            var par_payroll_registry_nbrParameter = par_payroll_registry_nbr != null ?
                new ObjectParameter("par_payroll_registry_nbr", par_payroll_registry_nbr) :
                new ObjectParameter("par_payroll_registry_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollregistry_cafao_sub_rep_Result>("sp_payrollregistry_cafao_sub_rep", par_payroll_yearParameter, par_payroll_registry_nbrParameter);
        }
    
        public virtual ObjectResult<sp_payrollregistry_obr_rep_Result> sp_payrollregistry_obr_rep(string par_payroll_year, string par_payroll_registry_nbr, string par_payrolltemplate_code)
        {
            var par_payroll_yearParameter = par_payroll_year != null ?
                new ObjectParameter("par_payroll_year", par_payroll_year) :
                new ObjectParameter("par_payroll_year", typeof(string));
    
            var par_payroll_registry_nbrParameter = par_payroll_registry_nbr != null ?
                new ObjectParameter("par_payroll_registry_nbr", par_payroll_registry_nbr) :
                new ObjectParameter("par_payroll_registry_nbr", typeof(string));
    
            var par_payrolltemplate_codeParameter = par_payrolltemplate_code != null ?
                new ObjectParameter("par_payrolltemplate_code", par_payrolltemplate_code) :
                new ObjectParameter("par_payrolltemplate_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollregistry_obr_rep_Result>("sp_payrollregistry_obr_rep", par_payroll_yearParameter, par_payroll_registry_nbrParameter, par_payrolltemplate_codeParameter);
        }
    
        public virtual ObjectResult<sp_payrollregistry_oth1_rep_Result> sp_payrollregistry_oth1_rep(string par_payroll_year, string par_payroll_registry_nbr, string par_payrolltemplate_code)
        {
            var par_payroll_yearParameter = par_payroll_year != null ?
                new ObjectParameter("par_payroll_year", par_payroll_year) :
                new ObjectParameter("par_payroll_year", typeof(string));
    
            var par_payroll_registry_nbrParameter = par_payroll_registry_nbr != null ?
                new ObjectParameter("par_payroll_registry_nbr", par_payroll_registry_nbr) :
                new ObjectParameter("par_payroll_registry_nbr", typeof(string));
    
            var par_payrolltemplate_codeParameter = par_payrolltemplate_code != null ?
                new ObjectParameter("par_payrolltemplate_code", par_payrolltemplate_code) :
                new ObjectParameter("par_payrolltemplate_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollregistry_oth1_rep_Result>("sp_payrollregistry_oth1_rep", par_payroll_yearParameter, par_payroll_registry_nbrParameter, par_payrolltemplate_codeParameter);
        }
    
        public virtual ObjectResult<sp_payrollregistry_othpay_rep_Result> sp_payrollregistry_othpay_rep(string par_payroll_year, string par_payroll_registry_nbr, string par_payrolltemplate_code)
        {
            var par_payroll_yearParameter = par_payroll_year != null ?
                new ObjectParameter("par_payroll_year", par_payroll_year) :
                new ObjectParameter("par_payroll_year", typeof(string));
    
            var par_payroll_registry_nbrParameter = par_payroll_registry_nbr != null ?
                new ObjectParameter("par_payroll_registry_nbr", par_payroll_registry_nbr) :
                new ObjectParameter("par_payroll_registry_nbr", typeof(string));
    
            var par_payrolltemplate_codeParameter = par_payrolltemplate_code != null ?
                new ObjectParameter("par_payrolltemplate_code", par_payrolltemplate_code) :
                new ObjectParameter("par_payrolltemplate_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollregistry_othpay_rep_Result>("sp_payrollregistry_othpay_rep", par_payroll_yearParameter, par_payroll_registry_nbrParameter, par_payrolltemplate_codeParameter);
        }
    
        public virtual ObjectResult<sp_payrollregistry_salary_ce_rep_Result> sp_payrollregistry_salary_ce_rep(string par_payroll_year, string par_payroll_registry_nbr, string par_payrolltemplate_code)
        {
            var par_payroll_yearParameter = par_payroll_year != null ?
                new ObjectParameter("par_payroll_year", par_payroll_year) :
                new ObjectParameter("par_payroll_year", typeof(string));
    
            var par_payroll_registry_nbrParameter = par_payroll_registry_nbr != null ?
                new ObjectParameter("par_payroll_registry_nbr", par_payroll_registry_nbr) :
                new ObjectParameter("par_payroll_registry_nbr", typeof(string));
    
            var par_payrolltemplate_codeParameter = par_payrolltemplate_code != null ?
                new ObjectParameter("par_payrolltemplate_code", par_payrolltemplate_code) :
                new ObjectParameter("par_payrolltemplate_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollregistry_salary_ce_rep_Result>("sp_payrollregistry_salary_ce_rep", par_payroll_yearParameter, par_payroll_registry_nbrParameter, par_payrolltemplate_codeParameter);
        }
    
        public virtual ObjectResult<sp_payrollregistry_salary_re_ce_rep_Result> sp_payrollregistry_salary_re_ce_rep(string par_payroll_year, string par_payroll_registry_nbr, string par_payrolltemplate_code)
        {
            var par_payroll_yearParameter = par_payroll_year != null ?
                new ObjectParameter("par_payroll_year", par_payroll_year) :
                new ObjectParameter("par_payroll_year", typeof(string));
    
            var par_payroll_registry_nbrParameter = par_payroll_registry_nbr != null ?
                new ObjectParameter("par_payroll_registry_nbr", par_payroll_registry_nbr) :
                new ObjectParameter("par_payroll_registry_nbr", typeof(string));
    
            var par_payrolltemplate_codeParameter = par_payrolltemplate_code != null ?
                new ObjectParameter("par_payrolltemplate_code", par_payrolltemplate_code) :
                new ObjectParameter("par_payrolltemplate_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollregistry_salary_re_ce_rep_Result>("sp_payrollregistry_salary_re_ce_rep", par_payroll_yearParameter, par_payroll_registry_nbrParameter, par_payrolltemplate_codeParameter);
        }
    
        public virtual ObjectResult<sp_payrollregistry_template_combolist_TRK_Result> sp_payrollregistry_template_combolist_TRK(string par_payrolltemplate_code)
        {
            var par_payrolltemplate_codeParameter = par_payrolltemplate_code != null ?
                new ObjectParameter("par_payrolltemplate_code", par_payrolltemplate_code) :
                new ObjectParameter("par_payrolltemplate_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollregistry_template_combolist_TRK_Result>("sp_payrollregistry_template_combolist_TRK", par_payrolltemplate_codeParameter);
        }
    
        public virtual ObjectResult<sp_payrolltemplate_tbl_list_Result> sp_payrolltemplate_tbl_list(string par_employment_type)
        {
            var par_employment_typeParameter = par_employment_type != null ?
                new ObjectParameter("par_employment_type", par_employment_type) :
                new ObjectParameter("par_employment_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrolltemplate_tbl_list_Result>("sp_payrolltemplate_tbl_list", par_employment_typeParameter);
        }
    
        public virtual int sp_tck_log_tbl_list(Nullable<byte> p_module_id, Nullable<int> p_year, Nullable<int> p_month, string p_tck_status)
        {
            var p_module_idParameter = p_module_id.HasValue ?
                new ObjectParameter("p_module_id", p_module_id) :
                new ObjectParameter("p_module_id", typeof(byte));
    
            var p_yearParameter = p_year.HasValue ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(int));
    
            var p_monthParameter = p_month.HasValue ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(int));
    
            var p_tck_statusParameter = p_tck_status != null ?
                new ObjectParameter("p_tck_status", p_tck_status) :
                new ObjectParameter("p_tck_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tck_log_tbl_list", p_module_idParameter, p_yearParameter, p_monthParameter, p_tck_statusParameter);
        }
    
        public virtual ObjectResult<sp_tck_status_list_Result> sp_tck_status_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tck_status_list_Result>("sp_tck_status_list");
        }
    
        public virtual ObjectResult<sp_tck_type_list_Result> sp_tck_type_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tck_type_list_Result>("sp_tck_type_list");
        }
    
        public virtual ObjectResult<sp_user_login_TRK_Result> sp_user_login_TRK(string par_user_id, string par_user_password)
        {
            var par_user_idParameter = par_user_id != null ?
                new ObjectParameter("par_user_id", par_user_id) :
                new ObjectParameter("par_user_id", typeof(string));
    
            var par_user_passwordParameter = par_user_password != null ?
                new ObjectParameter("par_user_password", par_user_password) :
                new ObjectParameter("par_user_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_user_login_TRK_Result>("sp_user_login_TRK", par_user_idParameter, par_user_passwordParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_tbl_rcvd_list_Result> sp_edocument_trk_tbl_rcvd_list(string p_department_code, Nullable<int> p_year, Nullable<int> p_month)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_yearParameter = p_year.HasValue ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(int));
    
            var p_monthParameter = p_month.HasValue ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_tbl_rcvd_list_Result>("sp_edocument_trk_tbl_rcvd_list", p_department_codeParameter, p_yearParameter, p_monthParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_tbl_retd_list_Result> sp_edocument_trk_tbl_retd_list(string p_department_code, Nullable<int> p_year, Nullable<int> p_month)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_yearParameter = p_year.HasValue ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(int));
    
            var p_monthParameter = p_month.HasValue ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_tbl_retd_list_Result>("sp_edocument_trk_tbl_retd_list", p_department_codeParameter, p_yearParameter, p_monthParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_tbl_rlsd_list_Result> sp_edocument_trk_tbl_rlsd_list(string p_department_code, Nullable<int> p_year, Nullable<int> p_month)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_yearParameter = p_year.HasValue ?
                new ObjectParameter("p_year", p_year) :
                new ObjectParameter("p_year", typeof(int));
    
            var p_monthParameter = p_month.HasValue ?
                new ObjectParameter("p_month", p_month) :
                new ObjectParameter("p_month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_tbl_rlsd_list_Result>("sp_edocument_trk_tbl_rlsd_list", p_department_codeParameter, p_yearParameter, p_monthParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_tbl_history_Result> sp_edocument_trk_tbl_history(string p_doc_ctrl_nbr, string p_docmnt_type)
        {
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            var p_docmnt_typeParameter = p_docmnt_type != null ?
                new ObjectParameter("p_docmnt_type", p_docmnt_type) :
                new ObjectParameter("p_docmnt_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_tbl_history_Result>("sp_edocument_trk_tbl_history", p_doc_ctrl_nbrParameter, p_docmnt_typeParameter);
        }
    
        public virtual ObjectResult<sp_document_tracking_tbl_2be_rlsd_cr_Result> sp_document_tracking_tbl_2be_rlsd_cr(string p_department_code, string p_role_id)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_role_idParameter = p_role_id != null ?
                new ObjectParameter("p_role_id", p_role_id) :
                new ObjectParameter("p_role_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_document_tracking_tbl_2be_rlsd_cr_Result>("sp_document_tracking_tbl_2be_rlsd_cr", p_department_codeParameter, p_role_idParameter);
        }
    
        public virtual int sp_document_tracking_correct_2_route(string p_department_code, string p_doc_ctrl_nbr)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_document_tracking_correct_2_route", p_department_codeParameter, p_doc_ctrl_nbrParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_correct_2_route_Result> sp_edocument_trk_correct_2_route(string p_department_code, string p_doc_ctrl_nbr)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_correct_2_route_Result>("sp_edocument_trk_correct_2_route", p_department_codeParameter, p_doc_ctrl_nbrParameter);
        }
    
        public virtual ObjectResult<sp_dtr_transmittal_hdr_tbl_list_ATS_Result> sp_dtr_transmittal_hdr_tbl_list_ATS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_transmittal_hdr_tbl_list_ATS_Result>("sp_dtr_transmittal_hdr_tbl_list_ATS");
        }
    
        public virtual ObjectResult<sp_dtr_transmittal_dtl_tbl_list_ATS_Result> sp_dtr_transmittal_dtl_tbl_list_ATS(string p_transmittal_nbr)
        {
            var p_transmittal_nbrParameter = p_transmittal_nbr != null ?
                new ObjectParameter("p_transmittal_nbr", p_transmittal_nbr) :
                new ObjectParameter("p_transmittal_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dtr_transmittal_dtl_tbl_list_ATS_Result>("sp_dtr_transmittal_dtl_tbl_list_ATS", p_transmittal_nbrParameter);
        }
    
        public virtual ObjectResult<sp_update_dtr_transmittal_hdr_tbl_ATS_Result> sp_update_dtr_transmittal_hdr_tbl_ATS(string p_transmittal_nbr)
        {
            var p_transmittal_nbrParameter = p_transmittal_nbr != null ?
                new ObjectParameter("p_transmittal_nbr", p_transmittal_nbr) :
                new ObjectParameter("p_transmittal_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_update_dtr_transmittal_hdr_tbl_ATS_Result>("sp_update_dtr_transmittal_hdr_tbl_ATS", p_transmittal_nbrParameter);
        }
    
        public virtual int sp_edocument_trk_transmit_insert_upd(string par_transmittal_nbr, string par_par_user_id, string par_update_type)
        {
            var par_transmittal_nbrParameter = par_transmittal_nbr != null ?
                new ObjectParameter("par_transmittal_nbr", par_transmittal_nbr) :
                new ObjectParameter("par_transmittal_nbr", typeof(string));
    
            var par_par_user_idParameter = par_par_user_id != null ?
                new ObjectParameter("par_par_user_id", par_par_user_id) :
                new ObjectParameter("par_par_user_id", typeof(string));
    
            var par_update_typeParameter = par_update_type != null ?
                new ObjectParameter("par_update_type", par_update_type) :
                new ObjectParameter("par_update_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_edocument_trk_transmit_insert_upd", par_transmittal_nbrParameter, par_par_user_idParameter, par_update_typeParameter);
        }
    
        public virtual ObjectResult<sp_edocument_trk_release_2_route_Result> sp_edocument_trk_release_2_route(string p_department_code, string p_doc_ctrl_nbr)
        {
            var p_department_codeParameter = p_department_code != null ?
                new ObjectParameter("p_department_code", p_department_code) :
                new ObjectParameter("p_department_code", typeof(string));
    
            var p_doc_ctrl_nbrParameter = p_doc_ctrl_nbr != null ?
                new ObjectParameter("p_doc_ctrl_nbr", p_doc_ctrl_nbr) :
                new ObjectParameter("p_doc_ctrl_nbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_trk_release_2_route_Result>("sp_edocument_trk_release_2_route", p_department_codeParameter, p_doc_ctrl_nbrParameter);
        }
    
        public virtual ObjectResult<sp_edocument_tk_2be_release_new_Result> sp_edocument_tk_2be_release_new(string par_department_code, string par_user)
        {
            var par_department_codeParameter = par_department_code != null ?
                new ObjectParameter("par_department_code", par_department_code) :
                new ObjectParameter("par_department_code", typeof(string));
    
            var par_userParameter = par_user != null ?
                new ObjectParameter("par_user", par_user) :
                new ObjectParameter("par_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_edocument_tk_2be_release_new_Result>("sp_edocument_tk_2be_release_new", par_department_codeParameter, par_userParameter);
        }
    }
}
